const monte = (min, max) => (Math.random() * (max - min) + min).toFixed(2);

export const mockCollections = [
  {
    id: 'incendios-arg',
    handle: 'incendios-argentina-2025',
    titulo: 'Incendios forestales en Argentina 2025',
    descripcion: 'Seguimiento nacional de focos activos y reportes validados con loaders proxy y dinámicos.',
    tags: ['Incendios', 'Bosques', 'Argentina'],
    consenso: 'Múltiples menciones',
    estado: 'curado',
    ultimaActualizacion: '2025-11-12T13:40:00Z',
    totalHechos: 327,
    fuentes: ['loader-estatico', 'loader-dinamico', 'loader-proxy'],
    hechos: [
      {
        id: 'INC-001',
        titulo: 'Foco activo en lago Mascardi',
        descripcion: 'El servicio dinámico reportó reactivación de incendio a 12 km de Bariloche.',
        categoria: 'Incendio forestal',
        fecha: '2025-10-04',
        fechaDeCarga: '2025-10-05',
        ubicacionLat: '-41.13',
        ubicacionLon: '-71.31',
        provincia: 'Río Negro',
        etiqueta: 'Alta prioridad',
        tipoHecho: 'TEXTO',
        fuente: 'loader_dinamico',
        fuenteNombre: 'Loader Dinámico Patagonia',
        adjuntos: [
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Foco+Mascardi', tipo: 'imagen' },
          { url: 'reporte_incendio.pdf', tipo: 'PDF' }
        ],
        consenso: true,
      },
      {
        id: 'INC-032',
        titulo: 'Cortafuegos en Traslasierra',
        descripcion: 'Fuentes proxy y dinámicas reportaron humo en Mina Clavero, Bomberos activaron protocolo.',
        categoria: 'Incendio forestal',
        fecha: '2025-09-28',
        fechaDeCarga: '2025-09-29',
        ubicacionLat: '-31.72',
        ubicacionLon: '-65.00',
        provincia: 'Córdoba',
        etiqueta: 'Seguimiento',
        tipoHecho: 'TEXTO',
        fuente: 'loader_proxy',
        fuenteNombre: 'Metamapa Córdoba',
        adjuntos: [
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Cortafuegos', tipo: 'imagen' },
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Humo', tipo: 'imagen' }
        ],
        consenso: true,
      },
      {
        id: 'INC-044',
        titulo: 'Restablecido foco en Ituzaingó',
        descripcion: 'CONAE detectó punto caliente, loader estático importó dataset del SINAGIR.',
        categoria: 'Incendio forestal',
        fecha: '2025-11-03',
        fechaDeCarga: '2025-11-03',
        ubicacionLat: '-27.60',
        ubicacionLon: '-56.69',
        provincia: 'Corrientes',
        etiqueta: 'Normalizado',
        tipoHecho: 'TEXTO',
        fuente: 'loader_estatico',
        fuenteNombre: 'Dataset SINAGIR 2025',
        adjuntos: [],
        consenso: false,
      },
      {
        id: 'INC-057',
        titulo: 'Prevención en Calamuchita',
        descripcion: 'Rondas de brigadistas con drones para validar columnas de humo cercanas al dique.',
        categoria: 'Incendio forestal',
        fecha: '2025-10-22',
        fechaDeCarga: '2025-10-23',
        ubicacionLat: '-32.08',
        ubicacionLon: '-64.52',
        provincia: 'Córdoba',
        etiqueta: 'Preventivo',
        tipoHecho: 'MULTIMEDIA',
        fuente: 'loader_dinamico',
        fuenteNombre: 'Contribuyentes Valle de Calamuchita',
        adjuntos: [
             { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Drone+1', tipo: 'imagen' },
             { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Drone+2', tipo: 'imagen' }
        ],
        consenso: true,
      },
    ],
  },
  {
    id: 'contaminacion-bsas',
    handle: 'contaminacion-cuenca-bsas',
    titulo: 'Alertas ambientales Cuenca Matanza-Riachuelo',
    descripcion: 'Sensores ciudadanos y datasets ACUMAR para identificar vertidos, olores y peces muertos.',
    tags: ['Contaminación', 'Riachuelo', 'Buenos Aires'],
    consenso: 'Mayoría simple',
    estado: 'curado',
    ultimaActualizacion: '2025-11-14T09:15:00Z',
    totalHechos: 118,
    fuentes: ['loader-dinamico', 'loader-proxy'],
    hechos: [
      {
        id: 'ACU-011',
        titulo: 'Vertido industrial en Lanús',
        descripcion: 'Visualizadores reportaron cambio de color del agua y olor ácido intenso.',
        categoria: 'Vertido químico',
        fecha: '2025-11-10',
        fechaDeCarga: '2025-11-10',
        ubicacionLat: '-34.70',
        ubicacionLon: '-58.39',
        provincia: 'Buenos Aires',
        etiqueta: 'Alerta temprana',
        tipoHecho: 'TEXTO',
        fuente: 'loader_dinamico',
        fuenteNombre: 'Contribuyentes Zona Sur',
        adjuntos: [
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Vertido+1', tipo: 'imagen' },
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Vertido+2', tipo: 'imagen' },
          { url: 'informe_vertido.pdf', tipo: 'PDF' }
        ],
        consenso: true,
      },
      {
        id: 'ACU-014',
        titulo: 'Mortandad de peces en Puente Alsina',
        descripcion: 'Loader proxy Metamapa Rosario replicó reporte coincidente en su instancia.',
        categoria: 'Fauna afectada',
        fecha: '2025-11-09',
        fechaDeCarga: '2025-11-09',
        ubicacionLat: '-34.66',
        ubicacionLon: '-58.42',
        provincia: 'Buenos Aires',
        etiqueta: 'Confirmado',
        tipoHecho: 'MULTIMEDIA',
        fuente: 'loader_proxy',
        fuenteNombre: 'Metamapa Rosario',
        adjuntos: [
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Peces+1', tipo: 'imagen' },
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Peces+2', tipo: 'imagen' },
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Peces+3', tipo: 'imagen' },
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Peces+4', tipo: 'imagen' },
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Peces+5', tipo: 'imagen' }
        ],
        consenso: true,
      },
      {
        id: 'ACU-017',
        titulo: 'Olor cloacal sostenido en Barracas',
        descripcion: 'Dataset ACUMAR confirmó superación de umbral de sulfuro de hidrógeno.',
        categoria: 'Emisión gaseosa',
        fecha: '2025-11-12',
        fechaDeCarga: '2025-11-12',
        ubicacionLat: '-34.64',
        ubicacionLon: '-58.37',
        provincia: 'Buenos Aires',
        etiqueta: 'Monitoreo',
        tipoHecho: 'TEXTO',
        fuente: 'loader_estatico',
        fuenteNombre: 'Dataset ACUMAR 2025',
        adjuntos: [
          { url: 'reporte_acumar.pdf', tipo: 'PDF' }
        ],
        consenso: true,
      },
    ],
  },
  {
    id: 'violencia-institucional',
    handle: 'violencia-institucional-arg',
    titulo: 'Violencia institucional documentada 2023-2025',
    descripcion: 'Casos reportados por organismos de DDHH y fuentes proxy a partir de entregas previas.',
    tags: ['DDHH', 'Seguridad', 'Alertas'],
    consenso: 'Absoluta',
    estado: 'curado',
    ultimaActualizacion: '2025-11-07T22:20:00Z',
    totalHechos: 64,
    fuentes: ['loader-proxy', 'loader-dinamico'],
    hechos: [
      {
        id: 'DDHH-021',
        titulo: 'Detención arbitraria en Rosario',
        descripcion: 'Organización Andhes envió expediente digital, loader proxy replicó atributos.',
        categoria: 'Detención arbitraria',
        fecha: '2025-10-30',
        fechaDeCarga: '2025-11-01',
        ubicacionLat: '-32.95',
        ubicacionLon: '-60.66',
        provincia: 'Santa Fe',
        etiqueta: 'Solicitada revisión',
        tipoHecho: 'TEXTO',
        fuente: 'loader_proxy',
        fuenteNombre: 'Metamapa Rosario',
        adjuntos: [
          { url: 'expediente_andhes.pdf', tipo: 'PDF' },
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Evidencia+1', tipo: 'imagen' },
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Evidencia+2', tipo: 'imagen' },
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Evidencia+3', tipo: 'imagen' },
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Evidencia+4', tipo: 'imagen' },
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Evidencia+5', tipo: 'imagen' }
        ],
        consenso: true,
      },
      {
        id: 'DDHH-024',
        titulo: 'Uso indebido de la fuerza en Constitución',
        descripcion: 'Contribuyentes subieron videos y se abrió investigación en API administrativa.',
        categoria: 'Violencia policial',
        fecha: '2025-11-05',
        fechaDeCarga: '2025-11-06',
        ubicacionLat: '-34.62',
        ubicacionLon: '-58.38',
        provincia: 'CABA',
        etiqueta: 'Alta prioridad',
        tipoHecho: 'MULTIMEDIA',
        fuente: 'loader_dinamico',
        fuenteNombre: 'Uploader ciudadano',
        adjuntos: [
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Video+1', tipo: 'imagen' },
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Video+2', tipo: 'imagen' },
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Video+3', tipo: 'imagen' },
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Video+4', tipo: 'imagen' },
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Video+5', tipo: 'imagen' },
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Video+6', tipo: 'imagen' },
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Video+7', tipo: 'imagen' },
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Video+8', tipo: 'imagen' },
          { url: 'https://via.placeholder.com/800x400/1a1f35/4ade80?text=Video+9', tipo: 'imagen' }
        ],
        consenso: true,
      },
      {
        id: 'DDHH-026',
        titulo: 'Seguimiento a testigo protegido',
        descripcion: 'API proxy cruzó fuentes para validar la denuncia recibida en Córdoba capital.',
        categoria: 'Intimidación',
        fecha: '2025-11-11',
        fechaDeCarga: '2025-11-11',
        ubicacionLat: '-31.41',
        ubicacionLon: '-64.19',
        provincia: 'Córdoba',
        etiqueta: 'Bajo reserva',
        tipoHecho: 'TEXTO',
        fuente: 'loader_proxy',
        fuenteNombre: 'Metamapa Córdoba',
        adjuntos: [],
        consenso: true,
      },
    ],
  },
];
