export const mockHechos = [
  {
    id: 'H-001',
    titulo: 'Foco activo en lago Mascardi',
    categoria: 'Incendio forestal',
    descripcion: 'Reactivación de incendio en Parque Nacional Nahuel Huapi.',
    fecha: '2025-10-04',
    provincia: 'Río Negro',
    fuenteTipo: 'dinamica',
    fuenteNombre: 'Loader Dinámico Patagonia',
    modo: 'curado',
    lat: -41.138,
    lon: -71.31,
  },
  {
    id: 'H-002',
    titulo: 'Vertido industrial en Lanús',
    categoria: 'Vertido químico',
    descripcion: 'Cambio de color del agua y olor ácido intenso.',
    fecha: '2025-11-10',
    provincia: 'Buenos Aires',
    fuenteTipo: 'dinamica',
    fuenteNombre: 'Contribuyentes Zona Sur',
    modo: 'curado',
    lat: -34.7,
    lon: -58.39,
  },
  {
    id: 'H-003',
    titulo: 'Mortandad de peces en Puente Alsina',
    categoria: 'Fauna afectada',
    descripcion: 'Loader proxy Metamapa Rosario replicó reporte coincidente.',
    fecha: '2025-11-09',
    provincia: 'Buenos Aires',
    fuenteTipo: 'proxy',
    fuenteNombre: 'Metamapa Rosario',
    modo: 'curado',
    lat: -34.66,
    lon: -58.42,
  },
  {
    id: 'H-004',
    titulo: 'Uso indebido de la fuerza en Constitución',
    categoria: 'Violencia policial',
    descripcion: 'Contribuyentes subieron videos y se abrió investigación.',
    fecha: '2025-11-05',
    provincia: 'CABA',
    fuenteTipo: 'dinamica',
    fuenteNombre: 'Uploader ciudadano',
    modo: 'curado',
    lat: -34.62,
    lon: -58.38,
  },
  {
    id: 'H-005',
    titulo: 'Restablecido foco en Ituzaingó',
    categoria: 'Incendio forestal',
    descripcion: 'Dataset SINAGIR informó punto caliente.',
    fecha: '2025-11-03',
    provincia: 'Corrientes',
    fuenteTipo: 'estatica',
    fuenteNombre: 'Dataset SINAGIR 2025',
    modo: 'irrestricta',
    lat: -27.6,
    lon: -56.69,
  },
  {
    id: 'H-006',
    titulo: 'Olor cloacal sostenido en Barracas',
    categoria: 'Emisión gaseosa',
    descripcion: 'Dataset ACUMAR confirmó superación de umbral.',
    fecha: '2025-11-12',
    provincia: 'Buenos Aires',
    fuenteTipo: 'estatica',
    fuenteNombre: 'Dataset ACUMAR 2025',
    modo: 'curado',
    lat: -34.64,
    lon: -58.37,
  },
  {
    id: 'H-007',
    titulo: 'Prevención en Calamuchita',
    categoria: 'Incendio forestal',
    descripcion: 'Rondas de brigadistas con drones.',
    fecha: '2025-10-22',
    provincia: 'Córdoba',
    fuenteTipo: 'dinamica',
    fuenteNombre: 'Contribuyentes Calamuchita',
    modo: 'curado',
    lat: -32.08,
    lon: -64.52,
  },
  {
    id: 'H-008',
    titulo: 'Detención arbitraria en Rosario',
    categoria: 'Detención arbitraria',
    descripcion: 'Organización Andhes envió expediente digital.',
    fecha: '2025-10-30',
    provincia: 'Santa Fe',
    fuenteTipo: 'proxy',
    fuenteNombre: 'Metamapa Rosario',
    modo: 'curado',
    lat: -32.95,
    lon: -60.66,
  },
];
